Trix.config.lang =
  bold: "Bold"
  bullets: "Bullets"
  byte:  "Byte"
  bytes: "Bytes"
  captionPlaceholder: "Type a caption here…"
  code: "Code"
  editCaption: "Edit caption"
  indent: "Increase Level"
  italic: "Italic"
  link: "Link"
  numbers: "Numbers"
  outdent: "Decrease Level"
  quote: "Quote"
  superscript: "Superscript"
  subscript: "Subscript"
  redo: "Redo"
  remove: "Remove"
  underline: "Underline"
  undo: "Undo"
  unlink: "Unlink"
  urlPlaceholder: "Enter a URL…"
  GB: "GB"
  KB: "KB"
  MB: "MB"
  PB: "PB"
  TB: "TB"
